#############################################################################
# Makefile for building: cognitus
# Generated by qmake (2.01a) (Qt 4.8.7) on: Sun Nov 13 04:58:58 2016
# Project:  cognitus.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile cognitus.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -Dtest_itself -Ddebug_mode -Ddebug_msg_core -DQT_NO_DEBUG -DQT_TESTLIB_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -std=c++11 -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtTest -I/usr/include/qt4 -IC:/ydisk/program/boost_1_62_0/ -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtTest -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		core/Bend/Bend.cpp \
		core/Network/Interface/Input/Input.cpp \
		core/Network/Network.cpp \
		core/Node/Node.cpp \
		core/Network/ActiveBend/activebend.cpp \
		core/Node/InterfaceNode.cpp \
		core/Bend/BendOfFigure/BendOfFigure.cpp \
		core/Bend/FreeBend/FreeBend.cpp \
		core/Circuit/Circuit.cpp \
		core/Network/Interface/Output/Output.cpp \
		interface/InterfaceWindow.cpp \
		core/threadSynchronization/WaiterForCondition.cpp \
		core/Network/Interface/Interface.cpp \
		core/Network/test/testNetwork.cpp \
		core/Network/CircuitFinder/CircuitFinder.cpp \
		core/Network/Interface/Input/test/testInput.cpp \
		core/Network/CircuitFinder/test/testCircuitFinder.cpp \
		core/test/randomFunc.cpp \
		core/test/Debug_inspector.cpp \
		core/test/Speed_profiler.cpp moc_InterfaceWindow.cpp
OBJECTS       = main.o \
		Bend.o \
		Input.o \
		Network.o \
		Node.o \
		activebend.o \
		InterfaceNode.o \
		BendOfFigure.o \
		FreeBend.o \
		Circuit.o \
		Output.o \
		InterfaceWindow.o \
		WaiterForCondition.o \
		Interface.o \
		testNetwork.o \
		CircuitFinder.o \
		testInput.o \
		testCircuitFinder.o \
		randomFunc.o \
		Debug_inspector.o \
		Speed_profiler.o \
		moc_InterfaceWindow.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		cognitus.pro
QMAKE_TARGET  = cognitus
DESTDIR       = 
TARGET        = cognitus

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_InterfaceWindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: cognitus.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtTest.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtNetwork.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile cognitus.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtTest.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtNetwork.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile cognitus.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/cognitus1.0.0 || $(MKDIR) .tmp/cognitus1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/cognitus1.0.0/ && $(COPY_FILE) --parents core/Bend/Bend.h core/Network/Interface/Input/Input.h core/Network/Interface/Output/Output.h core/Network/Interface/Interface.h core/Network/Network.h core/Node/Node.h core/Network/ActiveBend/ActiveBend.h core/Node/InterfaceNode.h core/Bend/BendOfFigure/BendOfFigure.h core/Bend/FreeBend/FreeBend.h core/Circuit/Circuit.h interface/InterfaceWindow.h core/threadSynchronization/WaiterForCondition.h core/Network/CircuitFinder/CircuitFinder.h core/Network/Interface/Input/test/testInput.h core/Network/test/testNetwork.h core/test/allTests.h core/Network/CircuitFinder/test/testCircuitFinder.h core/test/randomFunc.h core/test/Debug_inspector.h core/test/Speed_profiler.h .tmp/cognitus1.0.0/ && $(COPY_FILE) --parents main.cpp core/Bend/Bend.cpp core/Network/Interface/Input/Input.cpp core/Network/Network.cpp core/Node/Node.cpp core/Network/ActiveBend/activebend.cpp core/Node/InterfaceNode.cpp core/Bend/BendOfFigure/BendOfFigure.cpp core/Bend/FreeBend/FreeBend.cpp core/Circuit/Circuit.cpp core/Network/Interface/Output/Output.cpp interface/InterfaceWindow.cpp core/threadSynchronization/WaiterForCondition.cpp core/Network/Interface/Interface.cpp core/Network/test/testNetwork.cpp core/Network/CircuitFinder/CircuitFinder.cpp core/Network/Interface/Input/test/testInput.cpp core/Network/CircuitFinder/test/testCircuitFinder.cpp core/test/randomFunc.cpp core/test/Debug_inspector.cpp core/test/Speed_profiler.cpp .tmp/cognitus1.0.0/ && $(COPY_FILE) --parents interface/InterfaceWindow.ui .tmp/cognitus1.0.0/ && (cd `dirname .tmp/cognitus1.0.0` && $(TAR) cognitus1.0.0.tar cognitus1.0.0 && $(COMPRESS) cognitus1.0.0.tar) && $(MOVE) `dirname .tmp/cognitus1.0.0`/cognitus1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/cognitus1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_InterfaceWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_InterfaceWindow.cpp
moc_InterfaceWindow.cpp: interface/InterfaceWindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) interface/InterfaceWindow.h -o moc_InterfaceWindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_InterfaceWindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_InterfaceWindow.h
ui_InterfaceWindow.h: interface/InterfaceWindow.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic interface/InterfaceWindow.ui -o ui_InterfaceWindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp interface/InterfaceWindow.h \
		core/Network/Network.h \
		core/Network/Interface/Input/Input.h \
		core/Network/Interface/Interface.h \
		core/Node/InterfaceNode.h \
		core/Node/Node.h \
		core/Bend/Bend.h \
		core/threadSynchronization/WaiterForCondition.h \
		core/Network/Interface/Output/Output.h \
		core/Network/ActiveBend/ActiveBend.h \
		core/Network/CircuitFinder/CircuitFinder.h \
		core/Circuit/Circuit.h \
		core/test/allTests.h \
		core/Network/test/testNetwork.h \
		core/Network/Interface/Input/test/testInput.h \
		core/Network/CircuitFinder/test/testCircuitFinder.h \
		core/test/randomFunc.h \
		core/test/Debug_inspector.h \
		core/test/Speed_profiler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

Bend.o: core/Bend/Bend.cpp core/Bend/Bend.h \
		core/Node/Node.h \
		core/Node/InterfaceNode.h \
		core/Network/Network.h \
		core/Network/Interface/Input/Input.h \
		core/Network/Interface/Interface.h \
		core/threadSynchronization/WaiterForCondition.h \
		core/Network/Interface/Output/Output.h \
		core/Network/ActiveBend/ActiveBend.h \
		core/Network/CircuitFinder/CircuitFinder.h \
		core/Circuit/Circuit.h \
		core/test/allTests.h \
		core/Network/test/testNetwork.h \
		core/Network/Interface/Input/test/testInput.h \
		core/Network/CircuitFinder/test/testCircuitFinder.h \
		core/test/randomFunc.h \
		core/test/Debug_inspector.h \
		core/test/Speed_profiler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Bend.o core/Bend/Bend.cpp

Input.o: core/Network/Interface/Input/Input.cpp core/Network/Interface/Input/Input.h \
		core/Network/Interface/Interface.h \
		core/Node/InterfaceNode.h \
		core/Node/Node.h \
		core/Bend/Bend.h \
		core/threadSynchronization/WaiterForCondition.h \
		core/Network/Network.h \
		core/Network/Interface/Output/Output.h \
		core/Network/ActiveBend/ActiveBend.h \
		core/Network/CircuitFinder/CircuitFinder.h \
		core/Circuit/Circuit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Input.o core/Network/Interface/Input/Input.cpp

Network.o: core/Network/Network.cpp core/Network/Network.h \
		core/Network/Interface/Input/Input.h \
		core/Network/Interface/Interface.h \
		core/Node/InterfaceNode.h \
		core/Node/Node.h \
		core/Bend/Bend.h \
		core/threadSynchronization/WaiterForCondition.h \
		core/Network/Interface/Output/Output.h \
		core/Network/ActiveBend/ActiveBend.h \
		core/Network/CircuitFinder/CircuitFinder.h \
		core/Circuit/Circuit.h \
		core/test/allTests.h \
		core/Network/test/testNetwork.h \
		core/Network/Interface/Input/test/testInput.h \
		core/Network/CircuitFinder/test/testCircuitFinder.h \
		core/test/randomFunc.h \
		core/test/Debug_inspector.h \
		core/test/Speed_profiler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Network.o core/Network/Network.cpp

Node.o: core/Node/Node.cpp core/Node/Node.h \
		core/Bend/Bend.h \
		core/Network/Network.h \
		core/Network/Interface/Input/Input.h \
		core/Network/Interface/Interface.h \
		core/Node/InterfaceNode.h \
		core/threadSynchronization/WaiterForCondition.h \
		core/Network/Interface/Output/Output.h \
		core/Network/ActiveBend/ActiveBend.h \
		core/Network/CircuitFinder/CircuitFinder.h \
		core/Circuit/Circuit.h \
		core/test/allTests.h \
		core/Network/test/testNetwork.h \
		core/Network/Interface/Input/test/testInput.h \
		core/Network/CircuitFinder/test/testCircuitFinder.h \
		core/test/randomFunc.h \
		core/test/Debug_inspector.h \
		core/test/Speed_profiler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Node.o core/Node/Node.cpp

activebend.o: core/Network/ActiveBend/activebend.cpp core/Network/ActiveBend/ActiveBend.h \
		core/Bend/Bend.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o activebend.o core/Network/ActiveBend/activebend.cpp

InterfaceNode.o: core/Node/InterfaceNode.cpp core/Node/InterfaceNode.h \
		core/Node/Node.h \
		core/Bend/Bend.h \
		core/Network/Network.h \
		core/Network/Interface/Input/Input.h \
		core/Network/Interface/Interface.h \
		core/threadSynchronization/WaiterForCondition.h \
		core/Network/Interface/Output/Output.h \
		core/Network/ActiveBend/ActiveBend.h \
		core/Network/CircuitFinder/CircuitFinder.h \
		core/Circuit/Circuit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o InterfaceNode.o core/Node/InterfaceNode.cpp

BendOfFigure.o: core/Bend/BendOfFigure/BendOfFigure.cpp core/Bend/BendOfFigure/BendOfFigure.h \
		core/Bend/Bend.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BendOfFigure.o core/Bend/BendOfFigure/BendOfFigure.cpp

FreeBend.o: core/Bend/FreeBend/FreeBend.cpp core/Bend/FreeBend/FreeBend.h \
		core/Bend/Bend.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FreeBend.o core/Bend/FreeBend/FreeBend.cpp

Circuit.o: core/Circuit/Circuit.cpp core/Circuit/Circuit.h \
		core/Bend/Bend.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Circuit.o core/Circuit/Circuit.cpp

Output.o: core/Network/Interface/Output/Output.cpp core/Network/Interface/Output/Output.h \
		core/Network/Interface/Interface.h \
		core/Node/InterfaceNode.h \
		core/Node/Node.h \
		core/Bend/Bend.h \
		core/threadSynchronization/WaiterForCondition.h \
		core/Network/Network.h \
		core/Network/Interface/Input/Input.h \
		core/Network/ActiveBend/ActiveBend.h \
		core/Network/CircuitFinder/CircuitFinder.h \
		core/Circuit/Circuit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Output.o core/Network/Interface/Output/Output.cpp

InterfaceWindow.o: interface/InterfaceWindow.cpp interface/InterfaceWindow.h \
		ui_InterfaceWindow.h \
		core/Network/Network.h \
		core/Network/Interface/Input/Input.h \
		core/Network/Interface/Interface.h \
		core/Node/InterfaceNode.h \
		core/Node/Node.h \
		core/Bend/Bend.h \
		core/threadSynchronization/WaiterForCondition.h \
		core/Network/Interface/Output/Output.h \
		core/Network/ActiveBend/ActiveBend.h \
		core/Network/CircuitFinder/CircuitFinder.h \
		core/Circuit/Circuit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o InterfaceWindow.o interface/InterfaceWindow.cpp

WaiterForCondition.o: core/threadSynchronization/WaiterForCondition.cpp core/threadSynchronization/WaiterForCondition.h \
		core/test/Debug_inspector.h \
		core/test/Speed_profiler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o WaiterForCondition.o core/threadSynchronization/WaiterForCondition.cpp

Interface.o: core/Network/Interface/Interface.cpp core/Network/Interface/Interface.h \
		core/Node/InterfaceNode.h \
		core/Node/Node.h \
		core/Bend/Bend.h \
		core/test/allTests.h \
		core/Network/test/testNetwork.h \
		core/Network/Interface/Input/test/testInput.h \
		core/Network/Network.h \
		core/Network/Interface/Input/Input.h \
		core/threadSynchronization/WaiterForCondition.h \
		core/Network/Interface/Output/Output.h \
		core/Network/ActiveBend/ActiveBend.h \
		core/Network/CircuitFinder/CircuitFinder.h \
		core/Circuit/Circuit.h \
		core/Network/CircuitFinder/test/testCircuitFinder.h \
		core/test/randomFunc.h \
		core/test/Debug_inspector.h \
		core/test/Speed_profiler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Interface.o core/Network/Interface/Interface.cpp

testNetwork.o: core/Network/test/testNetwork.cpp core/Network/test/testNetwork.h \
		core/Network/Interface/Input/test/testInput.h \
		core/Network/Network.h \
		core/Network/Interface/Input/Input.h \
		core/Network/Interface/Interface.h \
		core/Node/InterfaceNode.h \
		core/Node/Node.h \
		core/Bend/Bend.h \
		core/threadSynchronization/WaiterForCondition.h \
		core/Network/Interface/Output/Output.h \
		core/Network/ActiveBend/ActiveBend.h \
		core/Network/CircuitFinder/CircuitFinder.h \
		core/Circuit/Circuit.h \
		core/test/Debug_inspector.h \
		core/test/Speed_profiler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o testNetwork.o core/Network/test/testNetwork.cpp

CircuitFinder.o: core/Network/CircuitFinder/CircuitFinder.cpp core/Network/CircuitFinder/CircuitFinder.h \
		core/Circuit/Circuit.h \
		core/Bend/Bend.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CircuitFinder.o core/Network/CircuitFinder/CircuitFinder.cpp

testInput.o: core/Network/Interface/Input/test/testInput.cpp core/test/allTests.h \
		core/Network/test/testNetwork.h \
		core/Network/Interface/Input/test/testInput.h \
		core/Network/Network.h \
		core/Network/Interface/Input/Input.h \
		core/Network/Interface/Interface.h \
		core/Node/InterfaceNode.h \
		core/Node/Node.h \
		core/Bend/Bend.h \
		core/threadSynchronization/WaiterForCondition.h \
		core/Network/Interface/Output/Output.h \
		core/Network/ActiveBend/ActiveBend.h \
		core/Network/CircuitFinder/CircuitFinder.h \
		core/Circuit/Circuit.h \
		core/Network/CircuitFinder/test/testCircuitFinder.h \
		core/test/randomFunc.h \
		core/test/Debug_inspector.h \
		core/test/Speed_profiler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o testInput.o core/Network/Interface/Input/test/testInput.cpp

testCircuitFinder.o: core/Network/CircuitFinder/test/testCircuitFinder.cpp core/Network/CircuitFinder/test/testCircuitFinder.h \
		core/Network/Interface/Input/test/testInput.h \
		core/Network/Network.h \
		core/Network/Interface/Input/Input.h \
		core/Network/Interface/Interface.h \
		core/Node/InterfaceNode.h \
		core/Node/Node.h \
		core/Bend/Bend.h \
		core/threadSynchronization/WaiterForCondition.h \
		core/Network/Interface/Output/Output.h \
		core/Network/ActiveBend/ActiveBend.h \
		core/Network/CircuitFinder/CircuitFinder.h \
		core/Circuit/Circuit.h \
		core/test/randomFunc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o testCircuitFinder.o core/Network/CircuitFinder/test/testCircuitFinder.cpp

randomFunc.o: core/test/randomFunc.cpp core/test/randomFunc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o randomFunc.o core/test/randomFunc.cpp

Debug_inspector.o: core/test/Debug_inspector.cpp core/test/Debug_inspector.h \
		core/test/Speed_profiler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Debug_inspector.o core/test/Debug_inspector.cpp

Speed_profiler.o: core/test/Speed_profiler.cpp core/test/Speed_profiler.h \
		core/test/Debug_inspector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Speed_profiler.o core/test/Speed_profiler.cpp

moc_InterfaceWindow.o: moc_InterfaceWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_InterfaceWindow.o moc_InterfaceWindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

